services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: code_review
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Learner0123
    ports:
      - "5432:5432"
    volumes:
      - review_data:/var/lib/postgresql/data
volumes:
  review_data:
